config/routes.rb
Rails.application.routes.draw do
  resources :genres
  resources :users

  root "movies#index"

  get "movies/filter/:filter" => "movies#index", as: :filtered_movies

  resources :movies do
    resources :reviews
    resources :favorites, only: [:create, :destroy]
  end

  resource :session, only: [:new, :create, :destroy]

  get "signup" => "users#new"

end

app/models/movie.rb
class Movie < ApplicationRecord
  before_save :set_slug

  has_many :reviews, dependent: :destroy
  has_many :favorites, dependent: :destroy
  has_many :fans, through: :favorites, source: :user
  has_many :characterizations, dependent: :destroy
  has_many :genres, through: :characterizations

  has_one_attached :main_image

  validates :title, presence: true, uniqueness: true

  validates :released_on, :duration, presence: true

  validates :description, length: { minimum: 25 }

  validates :total_gross, numericality: { greater_than_or_equal_to: 0 }

  RATINGS = %w(G PG PG-13 R NC-17)

  validates :rating, inclusion: { in: RATINGS }

  validate :acceptable_image

  scope :released, -> { where("released_on < ?", Time.now).order("released_on desc") }

  scope :upcoming, -> { where("released_on > ?", Time.now).order("released_on asc") }

  scope :recent, ->(max=5) { released.limit(max) }

  def flop?
    total_gross.blank? || total_gross < 225_000_000
  end

  def average_stars
    reviews.average(:stars) || 0.0
  end

  def to_param
    slug
  end

private

  def set_slug
    self.slug = title.parameterize
  end

  def acceptable_image
    return unless main_image.attached?

    unless main_image.blob.byte_size <= 1.megabyte
      errors.add(:main_image, "is too big")
    end

    acceptable_types = ["image/jpeg", "image/png"]
    unless acceptable_types.include?(main_image.content_type)
      errors.add(:main_image, "must be a JPEG or PNG")
    end
  end
end

app/views/layouts/_flash.html.erb
<% if flash[:notice]%>
    <div class="flash notice">
        <%= flash[:notice] %>
    </div>
<% elsif flash[:alert]%>
    <div class="flash alert">
        <%= flash[:alert] %>
    </div>
<% end %>

app/views/layouts/_footer.html.erb
<footer>
    <p>
    Copyright &copy; <%= Time.now.year %>
    <%= link_to "Said's test store", "https://myteststore.ca" %>
    </p>
</footer>

app/views/layouts/_form.html.erb
<%= form_with(model: movie) do |f| %>
  <%= render "shared/errors", object: movie%>

  <%= f.label :title %>
  <%= f.text_field :title, autofocus: true %>

  <%= f.label :description %>
  <%= f.text_area :description, rows: 7 %>

  <%= f.label :rating%>
  <%= f.select :rating, Movie::RATINGS, prompt: "Pick one" %>

  <%= f.label :released_on %>
  <%= f.date_select :released_on, {}, {class: "date"} %>

  <%= f.label :total_gross %>
  <%= f.number_field :total_gross %>

  <%= f.label :director%>
  <%= f.text_field :director%>

  <%= f.label :duration%>
  <%= f.text_field :duration%>

  <%= f.label :main_image%>
  <%= f.file_field :main_image%>

  <div class="checkboxes">
    <%= f.collection_check_boxes(:genre_ids, Genre.order(:name), :id, :name)%>
  </div>

  <%= f.submit%>
<% end %>

app/views/layouts/_header.html.erb
<header>
    <nav>
        <%= link_to image_tag('logo.png'), root_path %>
        <ul class="left">
            <li>
            <%= link_to 'Released', movies_path %>
            </li>
            <li>
                <%= link_to 'Upcoming', filtered_movies_path(:upcoming) %>
            </li>
            <li>
                <%= link_to 'Recent', filtered_movies_path(:recent) %>
            </li>

        </ul>

        <ul class = 'right'>

            <% if current_user%>
                <li>
                    <%= link_to current_user.name, current_user %>
                </li>
                <li>
                    <%= link_to "Sign out", session_path, class: "button",
                                data: { turbo_method: :delete, turbo_confirm: "Are you sure?" }%>
                </li>
            <% else %>
                <li>
                    <%= link_to "Log in", new_session_path, class: "button"%>
                </li>
                <li>
                    <%= link_to "Signup", signup_path, class: "button"%>
                </li>
            <% end %>
        </ul>
    </nav>
</header>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Super-Heroic Flix</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= render "layouts/header"%>
    <div class="content">
      <%= render "layouts/flash"%>
      <%=yield%>
    </div>
    <%= render "layouts/footer"%>
  </body>
</html>